# Aug 24th Update
name: Verademo-actions-main-branches

on:
  push:
    branches:
      - main

jobs:
  build-sca-policyscan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    - name: Build with Maven
      run: mvn clean install
    
    # Run a Software Composition Analysis scan
    - run: curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan . --update-advisor 2>&1 | tee sca_output.txt
      env:
        SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}
    - uses: actions/upload-artifact@v2
      with:
        name: SCAScanResults
        path: sca_output.txt

    # Run a Policy Scan
    - uses: actions/upload-artifact@v2
      with:
        path: target/verademo.war
    - uses: veracode/veracode-uploadandscan-action@master
      with:
        appname: "Verademo-actions"
        filepath: 'target/verademo.war'
        vid: '${{ secrets.VERACODE_API_ID }}'
        vkey: '${{ secrets.VERACODE_API_KEY }}'
        createprofile: 'false'
