name: Verademo-Pipeline

on: [push]

jobs:
  build-pipelinescan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    - name: Build with Maven
      run: mvn clean verify
 
    - name: Veracode Static Analysis Pipeline Scan and SARIF import
      uses: veracode/veracode-pipeline-scan-results-to-sarif@v0.1.5
      with:
        pipeline-results-json: results.json
        output-results-sarif: veracode-results.sarif
        finding-rule-level: "4:3:0"

    - name: upload sarif file to repository
      uses: github/codeql-action/upload-sarif@v1
      with: # Path to SARIF file relative to the root of the repository
        sarif_file: veracode-results.sarif
