name: Verademo-Pipeline

on: [push]

jobs:
  build-pipelinescan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    - name: Build with Maven
      run: mvn clean verify

    - name: Download the Pipeline Scanner
      uses: wei/curl@master
      with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    
    - name: Unzip the Pipeline Scanner
      run: unzip pipeline-scan-LATEST.zip pipeline-scan.jar
 
    - name: Run Pipeline Scan
      run: java -jar pipeline-scan.jar -f /home/runner/work/verademo-actions/verademo-actions/target/verademo.war -vid "${{secrets.VERACODE_API_ID}}" -vkey "${{secrets.VERACODE_API_KEY}}" --fail_on_severity="Very High, High" --issue_details true -jo true
      continue-on-error: true

    - name: Veracode Static Analysis Pipeline Scan SARIF import
      uses: veracode/veracode-pipeline-scan-results-to-sarif@v0.1.5
      with: #default json output
        pipeline-results-json: results.json
        output-results-sarif: veracode-results.sarif
        finding-rule-level: "4:3:0"

    - name: upload sarif file to repository
      uses: github/codeql-action/upload-sarif@v1
      with: # Path to SARIF file relative to the root of the repository
        sarif_file: veracode-results.sarif
